jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Tap local formula
      run: brew tap-new --no-git local/dystemctl && cp Formula/dystemctl.rb $(brew
        --repository local/dystemctl)/Formula/
    - name: Install from source
      run: brew install --build-from-source --verbose local/dystemctl/dystemctl
    - name: Test systemctl
      run: brew test local/dystemctl/dystemctl
    - name: Test commands
      run: 'systemctl --help

        journalctl --help

        systemctl status | head -20

        '
name: Homebrew
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch: {}
