jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check flake
      run: nix flake check
    - name: Build package
      run: nix build
    - name: Test systemctl --help
      run: nix run .#systemctl -- --help
    - name: Test journalctl --help
      run: nix run .#journalctl -- --help
name: Nix
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch: {}
